// <auto-generated />
namespace GamingApp.Domain.DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class GamingAppMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GamingAppMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201910061825593_GamingAppMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
